resources:
  Resources:
    RoomsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_ROOMS}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: room_id
            AttributeType: S
          - AttributeName: room_name
            AttributeType: S
          - AttributeName: availability
            AttributeType: S
          - AttributeName: price_per_night
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: room_id
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: ${self:provider.environment.INDEXLSI1_ROOMS}
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: room_name
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.INDEXGSI1_ROOMS}
            KeySchema:
              - AttributeName: availability
                KeyType: HASH
              - AttributeName: tenant_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
