org: mateormz
service: room-api

provider:
  name: aws
  runtime: python3.9
  iam:
    role: arn:aws:iam::187978737113:role/LabRoles
  memorySize: 1024
  timeout: 30
  environment:
    TABLE_ROOMS: ${sls:stage}-hotel-rooms
    INDEXLSI1_ROOMS: tenant-room_name-index
    INDEXGSI1_ROOMS: is_available-index
    SERVICE_NAME: user-api  # Nombre del servicio que contiene la validación de token
    STAGE: ${sls:stage}

functions:
  room_create:
    handler: createRoom.lambda_handler
    events:
      - http:
          path: /room/create
          method: post
          cors: true

  room_update:
    handler: updateRoom.lambda_handler
    events:
      - http:
          path: /room/{tenant_id}/{room_id}
          method: put
          cors: true

  room_delete:
    handler: deleteRoom.lambda_handler
    events:
      - http:
          path: /room/{tenant_id}/{room_id}
          method: delete
          cors: true

  room_getAllByTenant:
    handler: getAllRoomsByTenant.lambda_handler
    events:
      - http:
          path: /rooms/{tenant_id}
          method: get
          cors: true

  room_toggleAvailability:
    handler: toggleAvailability.lambda_handler
    events:
      - http:
          path: /room/toggleAvailability/{tenant_id}/{room_id}
          method: post
          cors: true

  room_getAll:
    handler: getAllRooms.lambda_handler
    events:
      - http:
          path: /rooms/all
          method: get
          cors: true

resources:
  Resources:
    RoomsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_ROOMS}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: room_id
            AttributeType: S
          - AttributeName: room_name
            AttributeType: S
          - AttributeName: is_available
            AttributeType: BOOL
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: room_id
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: ${self:provider.environment.INDEXLSI1_ROOMS}
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: room_name
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.INDEXGSI1_ROOMS}
            KeySchema:
              - AttributeName: is_available
                KeyType: HASH
              - AttributeName: tenant_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
