org: mateormz
service: comment-api

provider:
  name: aws
  runtime: python3.9
  iam:
    role: arn:aws:iam::637423324074:role/LabRole
  memorySize: 1024
  timeout: 30
  environment:
    TABLE_COMMENTS: ${sls:stage}-hotel-comments
    SERVICE_NAME: user-api
    STAGE: ${sls:stage}

functions:
  comment_create:
    handler: createComment.lambda_handler
    events:
      - http:
          path: /comment/create
          method: post
          cors: true
          integration: lambda

  comment_delete:
    handler: deleteComment.lambda_handler
    events:
      - http:
          path: /comment/{tenant_id}/{comment_id}
          method: delete
          cors: true
          integration: lambda

  comment_getByRoom:
    handler: getCommentsByRoom.lambda_handler
    events:
      - http:
          path: /comments/{tenant_id}/{room_id}
          method: get
          cors: true
          integration: lambda

  comment_getByUser:
    handler: getCommentsByUser.lambda_handler
    events:
      - http:
          path: /comments/user/{tenant_id}/{user_id}
          method: get
          cors: true
          integration: lambda

  comment_update:
    handler: updateComment.lambda_handler
    events:
      - http:
          path: /comment/update/{tenant_id}/{comment_id}
          method: put
          cors: true
          integration: lambda

resources:
  Resources:
    CommentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_COMMENTS}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: comment_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: created_at
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: comment_id
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: tenant-room-index
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: room_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        GlobalSecondaryIndexes:
          - IndexName: user-date-index
            KeySchema:
              - AttributeName: user_id
                KeyType: HASH
              - AttributeName: created_at
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
