org: lopezluis17
service: comment-api

provider:
  name: aws
  runtime: python3.12
  environment:
    TABLE_NAME: ${sls:stage}-hotel-comments
    SERVICE_NAME: comment-api
    STAGE: ${sls:stage}
  iam:
    role: arn:aws:iam::418974378390:role/LabRole
  memorySize: 1024
  timeout: 30

functions:
  commentCreate:
    handler: createComment.lambda_handler
    events:
      - http:
          path: comments/
          method: post
          cors: true
          integration: lambda

  commentGetByRoom:
    handler: getCommentsByRoom.lambda_handler
    events:
      - http:
          path: comments/rooms/{tenant_id}/{room_id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                tenant_id: true
                room_id: true
          integration: lambda

  commentGetByUser:
    handler: getCommentsByUser.lambda_handler
    events:
      - http:
          path: comments/users/{tenant_id}/{user_id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                tenant_id: true
                user_id: true
          integration: lambda

  commentUpdate:
    handler: updateComment.lambda_handler
    events:
      - http:
          path: comments/{tenant_id}/{comment_id}
          method: put
          cors: true
          request:
            parameters:
              paths:
                tenant_id: true
                comment_id: true
          integration: lambda

  commentDelete:
    handler: deleteComment.lambda_handler
    events:
      - http:
          path: comments/{tenant_id}/{comment_id}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                tenant_id: true
                comment_id: true
          integration: lambda

resources:
  Resources:
    CommentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: comment_id
            AttributeType: S
          - AttributeName: room_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: comment_id
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: tenant-room-index
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: room_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        GlobalSecondaryIndexes:
          - IndexName: user-date-index
            KeySchema:
              - AttributeName: user_id
                KeyType: HASH
              - AttributeName: date
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
