org: aron18
service: payment-api

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role: arn:aws:iam::637423363021:role/LabRole
  memorySize: 1024
  timeout: 30
  environment:
    TABLE_PAYMENTS: ${sls:stage}-hotel-payments
    SERVICE_NAME: reservation-api  # Nombre del servicio que contiene la validación de token
    STAGE: ${sls:stage}

functions:
  payment_create:
    handler: src/payment.createPayment
    events:
      - http:
          path: /payment/create
          method: post
          cors: true
          integration: lambda

  payment_delete:
    handler: src/payment.deletePayment
    events:
      - http:
          path: /payment/{tenant_id}/{payment_id}
          method: delete
          cors: true
          integration: lambda

  payment_getAll:
    handler: src/payment.getAllPayments
    events:
      - http:
          path: /payments/{tenant_id}
          method: get
          cors: true
          integration: lambda

  payment_getById:
    handler: src/payment.getPaymentById
    events:
      - http:
          path: /payment/{tenant_id}/{payment_id}
          method: get
          cors: true
          integration: lambda

  payment_getByUserAndTenantId:
    handler: src/payment.getPaymentByUserAndTenantId
    events:
      - http:
          path: /payments/{tenant_id}/{user_id}
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    PaymentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_PAYMENTS}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: payment_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: reservation_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: payment_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
