org: joelm2405
service: payment-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iam:
    role: arn:aws:iam::187978737113:role/LabRole
  memorySize: 1024
  timeout: 30
  environment:
    TABLE_PAYMENTS: ${sls:stage}-hotel-payments
    SERVICE_NAME: reservation-api  # Nombre del servicio que contiene la validación de token
    STAGE: ${sls:stage}

functions:
  payment_create:
    handler: src/createPayment.createPayment
    events:
      - http:
          path: /payment/create
          method: post
          cors: true
          integration: lambda

  payment_delete:
    handler: src/deletePayment.deletePayment
    events:
      - http:
          path: /payment/{tenant_id}/{payment_id}
          method: delete
          cors: true
          integration: lambda

  payment_getAll:
    handler: src/getAllPayments.getAllPayments
    events:
      - http:
          path: /payments/{tenant_id}
          method: get
          cors: true
          integration: lambda

  payment_getById:
    handler: src/getPaymentById.getPaymentById
    events:
      - http:
          path: /payment/{tenant_id}/{payment_id}
          method: get
          cors: true
          integration: lambda

  payment_getByUserAndTenantId:
    handler: src/getPaymentsByUserAndTenantId.getPaymentsByUserAndTenantId
    events:
      - http:
          path: /payments/{tenant_id}/{user_id}
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    PaymentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_PAYMENTS}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S  # Definir el tipo como String (S)
          - AttributeName: payment_id
            AttributeType: S  # Definir el tipo como String (S)
          - AttributeName: user_id
            AttributeType: S  # Definir el tipo como String (S) para el índice
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH   # Clave principal de tipo HASH (tenant_id)
          - AttributeName: payment_id
            KeyType: RANGE  # Clave secundaria de tipo RANGE (payment_id)
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        GlobalSecondaryIndexes:
          - IndexName: user_id-tenant_id-index
            KeySchema:
              - AttributeName: user_id
                KeyType: HASH   # Clave primaria del índice secundaria (user_id)
              - AttributeName: tenant_id
                KeyType: RANGE  # Clave secundaria del índice (tenant_id)
            Projection:
              ProjectionType: ALL
