org: joelm2405
service: payment-api

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role: arn:aws:iam::637423363021:role/LabRole
  memorySize: 1024
  timeout: 30
  environment:
    TABLE_PAYMENTS: ${sls:stage}-hotel-payments
    TABLE_ROOMS: ${sls:stage}-hotel-rooms
    TABLE_SERVICES: ${sls:stage}-hotel-services
    TABLE_RESERVATIONS: ${sls:stage}-hotel-reservations
    SERVICE_NAME_USER: user-api
    STAGE: ${sls:stage}

functions:
  createPayment:
    handler: createPayment.createPayment
    events:
      - http:
          path: /payment/create
          method: post
          cors: true
          integration: lambda

  deletePayment:
    handler: deletePayment.deletePayment
    events:
      - http:
          path: /payment/{tenant_id}/{payment_id}
          method: delete
          cors: true
          integration: lambda

  getAllPayments:
    handler: getAllPayments.getAllPayments
    events:
      - http:
          path: /payments/{tenant_id}
          method: get
          cors: true
          integration: lambda

  getPaymentById:
    handler: getPaymentById.getPaymentById
    events:
      - http:
          path: /payment/{tenant_id}/{payment_id}
          method: get
          cors: true
          integration: lambda

  getPaymentByUserAndTenantId:
    handler: getPaymentByUserAndTenantId.getPaymentByUserAndTenantId
    events:
      - http:
          path: /payment/{tenant_id}/{user_id}
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    PaymentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_PAYMENTS}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: payment_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: payment_date  # Atributo para el LSI
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: payment_id
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: tenant-user-id-index
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: user_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        LocalSecondaryIndexes:
          - IndexName: tenant-payment-date-index
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: payment_date
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
