org: joelm2405
service: payment-api

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role: arn:aws:iam::637423363021:role/LabRole
  environment:
    TABLE_PAYMENTS: ${self:stage}-hotel-payments
    TABLE_ROOMS: ${self:stage}-hotel-rooms
    TABLE_SERVICES: ${self:stage}-hotel-services
    TABLE_RESERVATIONS: ${self:stage}-hotel-reservations
    SERVICE_NAME_USER: user-api
    STAGE: ${self:stage}
    INDEXGSI1_PAYMENTS: ${self:provider.environment.TABLE_PAYMENTS}-user-id-index  # GSI para usuario
    INDEXLSI1_PAYMENTS: ${self:provider.environment.TABLE_PAYMENTS}-payment-date-index  # LSI para fecha de pago

functions:
  createPayment:
    handler: createPayment.createPayment
    events:
      - http:
          path: /payment/create
          method: post
          cors: true
          integration: lambda

  deletePayment:
    handler: deletePayment.deletePayment
    events:
      - http:
          path: /payment/{tenant_id}/{payment_id}
          method: delete
          cors: true
          integration: lambda

  getAllPayments:
    handler: getAllPayments.getAllPayments
    events:
      - http:
          path: /payments/{tenant_id}
          method: get
          cors: true
          integration: lambda

  getPaymentById:
    handler: getPaymentById.getPaymentById
    events:
      - http:
          path: /payment/{tenant_id}/{payment_id}
          method: get
          cors: true
          integration: lambda

  getPaymentByUserAndTenantId:
    handler: getPaymentByUserAndTenantId.getPaymentByUserAndTenantId
    events:
      - http:
          path: /payment/{tenant_id}/{user_id}
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    PaymentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_PAYMENTS}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: payment_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: payment_date
            AttributeType: S  # Usado para el LSI
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: payment_id
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.INDEXGSI1_PAYMENTS}
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: user_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        LocalSecondaryIndexes:
          - IndexName: ${self:provider.environment.INDEXLSI1_PAYMENTS}
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: payment_date
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true  # Habilitamos recuperación en el tiempo

